POST http://localhost:8080/api/v1/owner/my/upload
Content-Type: multipart/form-data; boundary=boundary
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibWVtYmVyVHlwZSI6Ik8iLCJyb2xlcyI6WyJST0xFX09XTkVSIl0sImlhdCI6MTY1MDg3Nzk0MCwiZXhwIjoxNjgyNDEzOTQwfQ.-gt1fQGtluspUoqtUsMSCNdrbuaqqV7NOvia7d1rjeE

--boundary
Content-Disposition: form-data; name="file"; filename="sample.img"

< ../../static/img/sample.jpg
--boundary


