### 핸드폰 사용가능 (200)
POST http://localhost:8080/api/v1/owner/auth/signup/validation/phone
Content-Type: application/json

{
  "phone": "01087654321"
}

### 중복 핸드폰 조회 (409)
POST http://localhost:8080/api/v1/owner/auth/signup/validation/phone
Content-Type: application/json

{
  "phone": "01012345678"
}

