POST http://localhost:8080/api/v1/owner/my/store/5/item
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwibWVtYmVyVHlwZSI6Ik8iLCJyb2xlcyI6WyJST0xFX09XTkVSIl0sImlhdCI6MTY1MDg3Nzk0MCwiZXhwIjoxNjgyNDEzOTQwfQ.-gt1fQGtluspUoqtUsMSCNdrbuaqqV7NOvia7d1rjeE

{
  "name": "사과",
  "description": "싱싱한 사과입니다.",
  "purchaseUnit": "1박스 (30개)",
  "imgUrl": "1/d4f87dd9-a52d-4808-86b5-b5acc2c36e8c.img",
  "price": 30000,
  "onSale": true
}
