### 수정 성공 (200)
PATCH http://localhost:8080/api/v1/users/info
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwibWVtYmVyVHlwZSI6IlUiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjUwNjQ0OTg4LCJleHAiOjE2ODIxODA5ODh9.DDoPbAUtJjnsLCX3BqEAJngJo9wcRVndCUE5YmqjIQE

{
     "name": "gil",
     "phone": "01012345678",
     "nickname": "길동이123",
     "streetAddress": "서울시 xx구 xx동 xx대로",
     "detailedAddress": "xx동 xx호"
}

### 수정 실패 by 번호 중복 (409)
PATCH http://localhost:8080/api/v1/users/info
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwibWVtYmVyVHlwZSI6IlUiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjUwNjQ0OTg4LCJleHAiOjE2ODIxODA5ODh9.DDoPbAUtJjnsLCX3BqEAJngJo9wcRVndCUE5YmqjIQE

{
  "name": "gil",
  "phone": "01012345671",
  "nickname": "길동이123",
  "streetAddress": "서울시 xx구 xx동 xx대로",
  "detailedAddress": "xx동 xx호"
}