GET http://localhost:8080/api/v1/users/info
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1IiwibWVtYmVyVHlwZSI6IlUiLCJyb2xlcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNjUwNjQyMTIxLCJleHAiOjE2ODIxNzgxMjF9.UBbInTBNAM5OAgxtJcNVQJEY0Ei3kKOyUAItLIzFkrA